#/*
# * Parallel Graph Coloring: 
# * Author: Kartik Mankad 
# * Email: kmankad@ncsu.edu
# * Description: A simple library to read MatrixMarket graph files to CSR 
# */
TARGET=GraphReader

LIB_BUILD=1
DEBUG=1

include ../Makefile.common
