#/*
# * Parallel Graph Coloring: 
# * Author: Kartik Mankad 
# * Email: kmankad@ncsu.edu
# * Description: A simple serial implementation of the FirstFit algorithm
# */
TARGET=ParallelFirstFit

DEPS=GraphReader

DEBUG=1

include ../Makefile.common
